ТЗ 9
Ekaterina-Kirpi/java-filmorate pull request #2
Opened 2023-04-14 18:52 UTC by Ekaterina-Kirpi

2023-04-15 00:28 UTC, EvgenyKoptubenko commented
Не все проверки пройдены Films API Tests / build / check-repo (pull_request) Failing after 4s

2023-04-15 00:32 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/HomeController.java
> +public class HomeController {
Между прочем это хорошая идея иметь home ресурс или какой-то базовый ресурс, с которого начинается все апи. Такой подход используется в Hateos.

Так же используют одинаково называющиеся эндпоинты между всеми АПИ в компании, например, admin/healthcheck, которые используются для отладки, мониторинга.

2023-04-15 00:33 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean isFilmValid = false;
Эта переменная не используется дальше нигде. Больше похоже на переменную, которая должна быть локальна в рамках функции

2023-04-15 00:34 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int MAX_DESCRIPTION_LENGTH = 200;
Эта переменная может быть final

2023-04-15 00:38 UTC, EvgenyKoptubenko commented
Если указать неверную дату выпуска фильма, то приходит 500-я ошибка
javax.validation.ValidationException: Неверно указана дата выпуска
	at ru.yandex.practicum.filmorate.controller.FilmController.validateFilm(FilmController.java:62)
{
	"timestamp": "2023-04-15T00:36:40.585+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films"
}


curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"FilmName",
	"description":"descriptionItem",
	"duration": 22,
	"releaseDate": "1012-04-23T18:25:43.511Z"
}'

Все-таки это не 500, а должна быть 400-я ошибка, т.к. это ошибка входных данных.
Если есть желание, попробуй выдать в ответ на неверные данные, ответ Bad Request

2023-04-15 00:41 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть несколько предложений по улучшению кода и проверки не все проходят

2023-04-18 10:39 UTC, Ekaterina-Kirpi commented
> Не все проверки пройдены Films API Tests / build / check-repo (pull_request) Failing after 4s

2023-04-18 11:41 UTC, Ekaterina-Kirpi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int MAX_DESCRIPTION_LENGTH = 200;
Сделала)

2023-04-18 11:52 UTC, Ekaterina-Kirpi commented on src/main/java/ru/yandex/practicum/filmorate/controller/HomeController.java
> +public class HomeController {
Сделала) Так же получилось вернуть нужный статус и Bad Request. И тесты прошли, хотя с ними было сложно) Спасибо!

2023-04-19 00:09 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-04-25 08:17 UTC, merged