Add friends likes
Ekaterina-Kirpi/java-filmorate pull request #3
Opened 2023-04-29 22:07 UTC by Ekaterina-Kirpi

Вынесено хранение данных о фильмах и пользователях в отдельные классы Storage. Добавлена бизнес-логика в классах Service. Внедрены зависимости.

2023-04-30 00:58 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getReleaseDate().isBefore(minReleaseDate)) {
Код дублируется с кодом из InMemoryFilmStorage

2023-04-30 01:00 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            log.warn("Пользователи не друзья",
Нет плейсхолдеров и значение переменных не выведется

2023-04-30 01:02 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getEmail() == null || user.getEmail().isEmpty() || !user.getEmail().contains("@") || user.getEmail().isBlank()) {
Код проверки тоже дублируется в InMemoryUserStorage.java

2023-04-30 01:07 UTC, EvgenyKoptubenko commented
Если есть желание, попробуй настроить ExceptionHandler для централизованной обработки ошибок

2023-04-30 01:08 UTC, EvgenyKoptubenko commented
Если отправить такой запрос, то падает с NullPointerException
curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"FilmName",
	"email":"email@email.com",
  "login":"login",
	"birthday":"2001-01-01",
	"duration":22
}'

java.lang.NullPointerException: null
	at ru.yandex.practicum.filmorate.service.FilmService.validateFilm(FilmService.java:86) ~[classes/:na]
	at ru.yandex.practicum.filmorate.service.FilmService.createFilm(FilmService.java:36) ~[classes/:na]
	at ru.yandex.practicum.filmorate.controller.FilmController.create(FilmController.java:29)

2023-04-30 01:09 UTC, EvgenyKoptubenko commented
Есть отправить запрос на создание друзей несколько раз, то приходит 400 Bad Request, но тут больше подходит Conflict - : Пользователи уже друзья
curl --request PUT \
  --url http://localhost:8080/users/1/friends/3 \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"nameItem",
	"email":"email3@email.com"
}'

2023-04-30 01:11 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть предложения по улучшению кода.

2023-05-03 03:14 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-05-17 08:25 UTC, Ekaterina-Kirpi commented
> Если есть желание, попробуй настроить ExceptionHandler для централизованной обработки ошибок

У меня не получилось(

2023-05-17 08:26 UTC, merged