Add database
Ekaterina-Kirpi/java-filmorate pull request #4
Opened 2023-05-23 22:17 UTC by Ekaterina-Kirpi

2023-05-23 22:58 UTC, EvgenyKoptubenko commented
в файле README.md должна быть ссылка на файл диаграммы.

2023-05-23 23:01 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.loadFilmGenres(filmStorage.getFilms());
попробуй выбирать жанры в одном селекте с фильмами и тогда не понадобится сперва вытаскивать отдельно все фильмы, потом все жанры этих фильмов, а потом раскладывать жанры по фильмам

2023-05-23 23:04 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/test/FilmStorageTest.java
> +    void getFilmBadId() {
Пустой тест не нужен. Либо его нужно удалить, либо написать

2023-05-23 23:07 UTC, EvgenyKoptubenko commented on pom.xml
>  			<artifactId>spring-boot-starter-test</artifactId>
Эта зависимость появляется два раза в pom

2023-05-23 23:08 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Field Injection считается не кошерным
https://stackoverflow.com/questions/39890849/what-exactly-is-field-injection-and-how-to-avoid-it

Если проходили это, то лучше переделать, если нет, то не обязательно

2023-05-23 23:10 UTC, EvgenyKoptubenko commented
curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"FilmName",
	"email":"email@email.com",
  "login":"login",
	"birthday":"2001-01-01",
	"description":"film Description",
	"duration":22
}'

Запрос, конечно, не верен, но лучше, если бы на него отвечали Bad Request, а не падал код с NullPointer Exception

2023-05-23 23:12 UTC, EvgenyKoptubenko commented
Если добавить лайк два раза, то приходит 500-я ошибка
INSERT INTO likes (film_id, user_id) VALUES (?,?) [23505-214]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_4514 ON PUBLIC.LIKES(FILM_ID NULLS FIRST, USER_ID NULLS FIRST) VALUES ( /* key:1 */ 1, 1)"; SQL statement:
INSERT INTO likes (film_id, user_id) VALUES (?,?) [23505-214]] with root cause

org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_4514 ON PUBLIC.LIKES(FILM_ID NULLS FIRST, USER_ID NULLS FIRST) VALUES ( /* key:1 */ 1, 1)"; SQL statement:
INSERT INTO likes (film_id, user_id) VALUES (?,?) [23505-214]

Можно ли добавить отмену лайка, либо прислать Conflict, либо 200, т.к. лайк уже есть

2023-05-23 23:13 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть предложения по улучшению кода

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +@EqualsAndHashCode(of = "id")
брать только айдишник для сравнения не очень хорошая идея. Бывают случаи, что айдишника нет, если он генерируется на стороне базы данных и в коде это может выстрелить исключением

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +@EqualsAndHashCode(of = "id")
аналогично верхнему комментарию

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +@RequiredArgsConstructor
эта аннотация тут лишняя. Она используется для создания конструктора из final  полей

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User implements Serializable {
если вы имплементируете этот интерфейс, то необходимо генерировать и добавлять serial id

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
лишняя пустая строка

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
все сервисы должны логировать все операции с сущностями(создание, обновление, получение, удаление)

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/service/LikeService.java
> +    @Autowired
эта аннотация тут лишняя. Инъекция через поле плохая идея, тем более у вас уже стоит аннотация для конструктора

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +    @Autowired
аналогично верхнему комментарию

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
лишняя пустая строка

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>  @Slf4j
необходимо добавить логирование по всем сервисам

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    @Autowired
все инъекции должны быть организованы через конструктор, убирайте эти аннотации

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    private final LocalDate minReleaseDate = LocalDate.of(1895, 12, 28);
из этого лучше сделать константу

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    @ResponseBody
эта аннотация тут бесполезна и метод лучше сделать приватным, так как используется только в этом классе

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FriendshipDbStorage.java
> +    @Autowired
инъекции зависимостей должны быть все через конструктор

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +    @Autowired
аналогично верхнему комментарию

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/LikeDbStorage.java
> +    private final FilmRowMapper filmRowMapper = new FilmRowMapper();
над этим классом вы поставили аннотацию компонент, значит его можно инжектить бином, а не создавать через new

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/MpaDbStorage.java
> +    @Autowired
инъекции через конструктор

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    @Autowired
инъекции через конструктор

2023-05-26 05:15 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +
лишняя пустая строка

2023-05-26 10:02 UTC, Ekaterina-Kirpi commented
Привет, замечания учла. Вот только данное все же осталось:  "брать только айдишник для сравнения не очень хорошая идея. Бывают случаи, что айдишника нет, если он генерируется на стороне базы данных и в коде это может выстрелить исключением"
тк в противном случае не верно сортируются жанры при выгрузке.

2023-08-08 08:36 UTC, merged